package postgres

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"
	"time"

	adminapp "github.com/csw/console/services/admin-api/internal/app/admin"
	domaincashier "github.com/csw/console/services/admin-api/internal/domain/cashier"
	"github.com/csw/console/services/admin-api/internal/domain/common"
)

type CashierRepo struct {
	db DBTX
}

func (r *CashierRepo) ListTemplates(ctx context.Context, page, pageSize int) ([]domaincashier.PriceTemplate, int, error) {
	offset := (page - 1) * pageSize
	rows, err := r.db.Query(ctx, `
SELECT id, template_id, template_name, fx_sync_enabled, fx_sync_mode, fx_sync_schedule, status
FROM platform.cashier_price_templates
ORDER BY updated_at DESC, id DESC
LIMIT $1 OFFSET $2`, pageSize, offset)
	if err != nil {
		return nil, 0, mapErr(err)
	}
	defer rows.Close()
	items := make([]domaincashier.PriceTemplate, 0)
	for rows.Next() {
		var it domaincashier.PriceTemplate
		if err := rows.Scan(&it.ID, &it.TemplateID, &it.TemplateName, &it.FXSyncEnabled, &it.FXSyncMode, &it.FXSyncSchedule, &it.Status); err != nil {
			return nil, 0, mapErr(err)
		}
		items = append(items, it)
	}
	var total int
	if err := r.db.QueryRow(ctx, `SELECT COUNT(*) FROM platform.cashier_price_templates`).Scan(&total); err != nil {
		return nil, 0, mapErr(err)
	}
	return items, total, mapErr(rows.Err())
}

func (r *CashierRepo) CreateTemplate(ctx context.Context, item domaincashier.PriceTemplate) (domaincashier.PriceTemplate, error) {
	var out domaincashier.PriceTemplate
	err := r.db.QueryRow(ctx, `
INSERT INTO platform.cashier_price_templates
  (template_id, template_name, fx_sync_enabled, fx_sync_mode, fx_sync_schedule, status)
VALUES ($1,$2,$3,$4,$5,$6)
RETURNING id, template_id, template_name, fx_sync_enabled, fx_sync_mode, fx_sync_schedule, status`,
		item.TemplateID, item.TemplateName, item.FXSyncEnabled, item.FXSyncMode, item.FXSyncSchedule, item.Status,
	).Scan(&out.ID, &out.TemplateID, &out.TemplateName, &out.FXSyncEnabled, &out.FXSyncMode, &out.FXSyncSchedule, &out.Status)
	return out, mapErr(err)
}

func (r *CashierRepo) GetTemplateByTemplateID(ctx context.Context, templateID string) (domaincashier.PriceTemplate, error) {
	return r.getTemplate(ctx, `template_id=$1`, templateID)
}

func (r *CashierRepo) GetTemplateByID(ctx context.Context, templateRowID int64) (domaincashier.PriceTemplate, error) {
	return r.getTemplate(ctx, `id=$1`, templateRowID)
}

func (r *CashierRepo) getTemplate(ctx context.Context, cond string, arg any) (domaincashier.PriceTemplate, error) {
	var out domaincashier.PriceTemplate
	err := r.db.QueryRow(ctx, `
SELECT id, template_id, template_name, fx_sync_enabled, fx_sync_mode, fx_sync_schedule, status
FROM platform.cashier_price_templates
WHERE `+cond, arg).Scan(
		&out.ID, &out.TemplateID, &out.TemplateName, &out.FXSyncEnabled, &out.FXSyncMode, &out.FXSyncSchedule, &out.Status,
	)
	return out, mapErr(err)
}

func (r *CashierRepo) ListVersions(ctx context.Context, templateIDRef int64) ([]domaincashier.TemplateVersionRecord, error) {
	rows, err := r.db.Query(ctx, `
SELECT id, template_id_ref, version, source_type, auto_generated, fx_base_date, status, checksum, published_at, created_at, updated_at
FROM platform.cashier_price_template_versions
WHERE template_id_ref=$1
ORDER BY CAST(version AS INTEGER) DESC, id DESC`, templateIDRef)
	if err != nil {
		return nil, mapErr(err)
	}
	defer rows.Close()
	out := make([]domaincashier.TemplateVersionRecord, 0)
	for rows.Next() {
		item, err := scanVersion(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, item)
	}
	return out, mapErr(rows.Err())
}

func (r *CashierRepo) GetVersionByTemplateAndVersion(ctx context.Context, templateIDRef int64, version int) (domaincashier.TemplateVersionRecord, error) {
	row := r.db.QueryRow(ctx, `
SELECT id, template_id_ref, version, source_type, auto_generated, fx_base_date, status, checksum, published_at, created_at, updated_at
FROM platform.cashier_price_template_versions
WHERE template_id_ref=$1 AND version=$2`, templateIDRef, version)
	return scanVersion(row)
}

func (r *CashierRepo) GetVersionByID(ctx context.Context, id int64) (domaincashier.TemplateVersionRecord, error) {
	row := r.db.QueryRow(ctx, `
SELECT id, template_id_ref, version, source_type, auto_generated, fx_base_date, status, checksum, published_at, created_at, updated_at
FROM platform.cashier_price_template_versions
WHERE id=$1`, id)
	return scanVersion(row)
}

func scanVersion(row interface{ Scan(dest ...any) error }) (domaincashier.TemplateVersionRecord, error) {
	var item domaincashier.TemplateVersionRecord
	var sourceType string
	var status string
	var versionString string
	err := row.Scan(
		&item.ID, &item.TemplateIDRef, &versionString, &sourceType, &item.AutoGenerated, &item.FXBaseDate,
		&status, &item.Checksum, &item.PublishedAt, &item.CreatedAt, &item.UpdatedAt,
	)
	if err != nil {
		return domaincashier.TemplateVersionRecord{}, mapErr(err)
	}
	v, convErr := strconv.Atoi(versionString)
	if convErr != nil {
		return domaincashier.TemplateVersionRecord{}, convErr
	}
	item.Version = v
	item.SourceType = domaincashier.SourceType(sourceType)
	item.Status = domaincashier.VersionStatus(status)
	return item, nil
}

func (r *CashierRepo) GetPublishedVersion(ctx context.Context, templateIDRef int64) (*domaincashier.TemplateVersionRecord, error) {
	row := r.db.QueryRow(ctx, `
SELECT id, template_id_ref, version, source_type, auto_generated, fx_base_date, status, checksum, published_at, created_at, updated_at
FROM platform.cashier_price_template_versions
WHERE template_id_ref=$1 AND status='published'
ORDER BY published_at DESC NULLS LAST, id DESC
LIMIT 1`, templateIDRef)
	item, err := scanVersion(row)
	if err != nil {
		if err == adminapp.ErrNotFound {
			return nil, nil
		}
		return nil, err
	}
	return &item, nil
}

func (r *CashierRepo) NextVersion(ctx context.Context, templateIDRef int64) (int, error) {
	var max int
	if err := r.db.QueryRow(ctx, `
SELECT COALESCE(MAX(CAST(version AS INTEGER)), 0)
FROM platform.cashier_price_template_versions
WHERE template_id_ref=$1`, templateIDRef).Scan(&max); err != nil {
		return 0, mapErr(err)
	}
	return max + 1, nil
}

func (r *CashierRepo) CreateVersion(ctx context.Context, version domaincashier.TemplateVersionRecord) (domaincashier.TemplateVersionRecord, error) {
	row := r.db.QueryRow(ctx, `
INSERT INTO platform.cashier_price_template_versions
  (template_id_ref, version, source_type, auto_generated, fx_base_date, status, checksum)
VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING id, template_id_ref, version, source_type, auto_generated, fx_base_date, status, checksum, published_at, created_at, updated_at`,
		version.TemplateIDRef, version.Version, string(version.SourceType), version.AutoGenerated, version.FXBaseDate,
		string(version.Status), version.Checksum,
	)
	return scanVersion(row)
}

func (r *CashierRepo) ArchiveVersion(ctx context.Context, versionID int64, at time.Time) error {
	_, err := r.db.Exec(ctx, `
UPDATE platform.cashier_price_template_versions
SET status='archived', updated_at=$2
WHERE id=$1`, versionID, at)
	return mapErr(err)
}

func (r *CashierRepo) PublishVersion(ctx context.Context, versionID int64, at time.Time, checksum string) error {
	_, err := r.db.Exec(ctx, `
UPDATE platform.cashier_price_template_versions
SET status='published', published_at=$2, updated_at=$2, checksum=$3
WHERE id=$1`, versionID, at, checksum)
	return mapErr(err)
}

func (r *CashierRepo) ListRows(ctx context.Context, versionID int64) ([]domaincashier.PriceRow, error) {
	rows, err := r.db.Query(ctx, `
SELECT id, template_version_id_ref, country_code, region_code, currency, price_id,
       pre_tax_amount_minor, tax_rate::text, tax_amount_minor, after_tax_amount_minor, effective_at
FROM platform.cashier_price_rows
WHERE template_version_id_ref=$1
ORDER BY country_code, region_code, currency, price_id`, versionID)
	if err != nil {
		return nil, mapErr(err)
	}
	defer rows.Close()
	out := make([]domaincashier.PriceRow, 0)
	for rows.Next() {
		var item domaincashier.PriceRow
		var effectiveAt time.Time
		if err := rows.Scan(
			&item.ID, &item.TemplateVersionIDRef, &item.CountryCode, &item.RegionCode, &item.Currency, &item.PriceID,
			&item.PreTaxAmountMinor, &item.TaxRate, &item.TaxAmountMinor, &item.AfterTaxAmountMinor, &effectiveAt,
		); err != nil {
			return nil, mapErr(err)
		}
		item.EffectiveAt = effectiveAt.UTC().Format(time.RFC3339)
		out = append(out, item)
	}
	return out, mapErr(rows.Err())
}

func (r *CashierRepo) ReplaceRows(ctx context.Context, versionID int64, rows []domaincashier.PriceRow) error {
	if _, err := r.db.Exec(ctx, `DELETE FROM platform.cashier_price_rows WHERE template_version_id_ref=$1`, versionID); err != nil {
		return mapErr(err)
	}
	for _, row := range rows {
		effectiveAt, err := time.Parse(time.RFC3339, row.EffectiveAt)
		if err != nil {
			return err
		}
		_, err = r.db.Exec(ctx, `
INSERT INTO platform.cashier_price_rows
  (template_version_id_ref, country_code, region_code, currency, price_id, pre_tax_amount_minor, tax_rate, tax_amount_minor, after_tax_amount_minor, effective_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,
			versionID, row.CountryCode, row.RegionCode, row.Currency, row.PriceID, row.PreTaxAmountMinor,
			row.TaxRate, row.TaxAmountMinor, row.AfterTaxAmountMinor, effectiveAt,
		)
		if err != nil {
			return mapErr(err)
		}
	}
	return nil
}

func (r *CashierRepo) CopyRows(ctx context.Context, sourceVersionID, targetVersionID int64) (int, error) {
	tag, err := r.db.Exec(ctx, `
INSERT INTO platform.cashier_price_rows
  (template_version_id_ref, country_code, region_code, currency, price_id, pre_tax_amount_minor, tax_rate, tax_amount_minor, after_tax_amount_minor, effective_at)
SELECT $2, country_code, region_code, currency, price_id, pre_tax_amount_minor, tax_rate, tax_amount_minor, after_tax_amount_minor, effective_at
FROM platform.cashier_price_rows
WHERE template_version_id_ref=$1`, sourceVersionID, targetVersionID)
	if err != nil {
		return 0, mapErr(err)
	}
	return int(tag.RowsAffected()), nil
}

func (r *CashierRepo) GetCurrencySpec(ctx context.Context, currency string) (common.CurrencySpec, error) {
	var spec common.CurrencySpec
	var roundingMode string
	err := r.db.QueryRow(ctx, `
SELECT currency_code, decimal_places, min_amount_minor, rounding_mode, enabled
FROM platform.currency_specs
WHERE currency_code=$1 AND enabled=TRUE`, currency).Scan(
		&spec.CurrencyCode, &spec.DecimalPlaces, &spec.MinAmountMinor, &roundingMode, &spec.Enabled,
	)
	if err != nil {
		return common.CurrencySpec{}, mapErr(err)
	}
	spec.RoundingMode = common.RoundingMode(roundingMode)
	return spec, nil
}

func (r *CashierRepo) CreateFXSyncRun(ctx context.Context, run domaincashier.FXSyncRun) (domaincashier.FXSyncRun, error) {
	diffRaw, err := json.Marshal(run.DiffSummaryJSON)
	if err != nil {
		return domaincashier.FXSyncRun{}, err
	}
	var out domaincashier.FXSyncRun
	var status string
	var raw []byte
	err = r.db.QueryRow(ctx, `
INSERT INTO platform.cashier_fx_sync_runs
  (template_id_ref, candidate_version_id_ref, status, diff_summary_json, review_note)
VALUES ($1,$2,$3,$4::jsonb,$5)
RETURNING id, template_id_ref, candidate_version_id_ref, status, diff_summary_json, triggered_at, reviewed_by, reviewed_at, review_note, created_at, updated_at`,
		run.TemplateIDRef, run.CandidateVersionIDRef, string(run.Status), string(diffRaw), run.ReviewNote,
	).Scan(
		&out.ID, &out.TemplateIDRef, &out.CandidateVersionIDRef, &status, &raw, &out.TriggeredAt,
		&out.ReviewedBy, &out.ReviewedAt, &out.ReviewNote, &out.CreatedAt, &out.UpdatedAt,
	)
	if err != nil {
		return domaincashier.FXSyncRun{}, mapErr(err)
	}
	_ = json.Unmarshal(raw, &out.DiffSummaryJSON)
	out.Status = domaincashier.FXRunStatus(status)
	return out, nil
}

func (r *CashierRepo) GetFXSyncRun(ctx context.Context, runID int64) (domaincashier.FXSyncRun, error) {
	var out domaincashier.FXSyncRun
	var status string
	var raw []byte
	err := r.db.QueryRow(ctx, `
SELECT id, template_id_ref, candidate_version_id_ref, status, diff_summary_json, triggered_at, reviewed_by, reviewed_at, review_note, created_at, updated_at
FROM platform.cashier_fx_sync_runs
WHERE id=$1`, runID).Scan(
		&out.ID, &out.TemplateIDRef, &out.CandidateVersionIDRef, &status, &raw, &out.TriggeredAt,
		&out.ReviewedBy, &out.ReviewedAt, &out.ReviewNote, &out.CreatedAt, &out.UpdatedAt,
	)
	if err != nil {
		return domaincashier.FXSyncRun{}, mapErr(err)
	}
	_ = json.Unmarshal(raw, &out.DiffSummaryJSON)
	out.Status = domaincashier.FXRunStatus(status)
	return out, nil
}

func (r *CashierRepo) ListFXSyncRuns(ctx context.Context, templateIDRef int64) ([]domaincashier.FXSyncRun, error) {
	rows, err := r.db.Query(ctx, `
SELECT id, template_id_ref, candidate_version_id_ref, status, diff_summary_json, triggered_at, reviewed_by, reviewed_at, review_note, created_at, updated_at
FROM platform.cashier_fx_sync_runs
WHERE template_id_ref=$1
ORDER BY triggered_at DESC, id DESC`, templateIDRef)
	if err != nil {
		return nil, mapErr(err)
	}
	defer rows.Close()
	out := make([]domaincashier.FXSyncRun, 0)
	for rows.Next() {
		var item domaincashier.FXSyncRun
		var status string
		var raw []byte
		if err := rows.Scan(
			&item.ID, &item.TemplateIDRef, &item.CandidateVersionIDRef, &status, &raw, &item.TriggeredAt,
			&item.ReviewedBy, &item.ReviewedAt, &item.ReviewNote, &item.CreatedAt, &item.UpdatedAt,
		); err != nil {
			return nil, mapErr(err)
		}
		_ = json.Unmarshal(raw, &item.DiffSummaryJSON)
		item.Status = domaincashier.FXRunStatus(status)
		out = append(out, item)
	}
	return out, mapErr(rows.Err())
}

func (r *CashierRepo) UpdateFXSyncRunReview(ctx context.Context, runID int64, status domaincashier.FXRunStatus, reviewer int64, reviewedAt time.Time, note string) error {
	_, err := r.db.Exec(ctx, `
UPDATE platform.cashier_fx_sync_runs
SET status=$2, reviewed_by=CASE WHEN $3=0 THEN NULL ELSE $3 END, reviewed_at=$4, review_note=$5, updated_at=$4
WHERE id=$1`, runID, string(status), reviewer, reviewedAt, note)
	return mapErr(err)
}

func (r *CashierRepo) ResolveGameRowID(ctx context.Context, gameID string) (int64, error) {
	var id int64
	if err := r.db.QueryRow(ctx, `SELECT id FROM games WHERE game_id=$1`, gameID).Scan(&id); err != nil {
		return 0, mapErr(err)
	}
	return id, nil
}

func (r *CashierRepo) GetGameCashierProfile(ctx context.Context, gameIDRef int64) (domaincashier.GameCashierProfile, error) {
	var out domaincashier.GameCashierProfile
	err := r.db.QueryRow(ctx, `
SELECT id, game_id_ref, template_id_ref, applied_template_version_id, snapshot_checksum, applied_at, created_at, updated_at
FROM game_cashier_profiles
WHERE game_id_ref=$1`, gameIDRef).Scan(
		&out.ID, &out.GameIDRef, &out.TemplateIDRef, &out.AppliedTemplateVersionID,
		&out.SnapshotChecksum, &out.AppliedAt, &out.CreatedAt, &out.UpdatedAt,
	)
	return out, mapErr(err)
}

func (r *CashierRepo) UpsertGameCashierProfile(ctx context.Context, profile domaincashier.GameCashierProfile) (domaincashier.GameCashierProfile, error) {
	var out domaincashier.GameCashierProfile
	err := r.db.QueryRow(ctx, `
INSERT INTO game_cashier_profiles (game_id_ref, template_id_ref, applied_template_version_id, snapshot_checksum, applied_at)
VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (game_id_ref) DO UPDATE
SET template_id_ref=EXCLUDED.template_id_ref,
    applied_template_version_id=EXCLUDED.applied_template_version_id,
    snapshot_checksum=EXCLUDED.snapshot_checksum,
    applied_at=EXCLUDED.applied_at,
    updated_at=NOW()
RETURNING id, game_id_ref, template_id_ref, applied_template_version_id, snapshot_checksum, applied_at, created_at, updated_at`,
		profile.GameIDRef, profile.TemplateIDRef, profile.AppliedTemplateVersionID, profile.SnapshotChecksum, profile.AppliedAt,
	).Scan(
		&out.ID, &out.GameIDRef, &out.TemplateIDRef, &out.AppliedTemplateVersionID,
		&out.SnapshotChecksum, &out.AppliedAt, &out.CreatedAt, &out.UpdatedAt,
	)
	return out, mapErr(err)
}

func (r *CashierRepo) ListGameCashierPriceOverrides(ctx context.Context, gameIDRef int64) ([]domaincashier.GameCashierPriceOverride, error) {
	rows, err := r.db.Query(ctx, `
SELECT id, game_id_ref, country_code, region_code, currency, price_id,
       pre_tax_amount_minor, tax_rate::text, tax_amount_minor, after_tax_amount_minor,
       reason, effective_at, created_at, updated_at
FROM game_cashier_price_overrides
WHERE game_id_ref=$1
ORDER BY country_code, region_code, currency, price_id`, gameIDRef)
	if err != nil {
		return nil, mapErr(err)
	}
	defer rows.Close()

	out := make([]domaincashier.GameCashierPriceOverride, 0)
	for rows.Next() {
		var item domaincashier.GameCashierPriceOverride
		if err := rows.Scan(
			&item.ID, &item.GameIDRef, &item.CountryCode, &item.RegionCode, &item.Currency, &item.PriceID,
			&item.PreTaxAmountMinor, &item.TaxRate, &item.TaxAmountMinor, &item.AfterTaxAmountMinor,
			&item.Reason, &item.EffectiveAt, &item.CreatedAt, &item.UpdatedAt,
		); err != nil {
			return nil, mapErr(err)
		}
		out = append(out, item)
	}
	return out, mapErr(rows.Err())
}

func (r *CashierRepo) ReplaceGameCashierPriceOverrides(ctx context.Context, gameIDRef int64, rows []domaincashier.GameCashierPriceOverride) error {
	if _, err := r.db.Exec(ctx, `DELETE FROM game_cashier_price_overrides WHERE game_id_ref=$1`, gameIDRef); err != nil {
		return mapErr(err)
	}
	for idx, row := range rows {
		_, err := r.db.Exec(ctx, `
INSERT INTO game_cashier_price_overrides
  (game_id_ref, country_code, region_code, currency, price_id, pre_tax_amount_minor, tax_rate, tax_amount_minor, after_tax_amount_minor, reason, effective_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,
			gameIDRef, row.CountryCode, row.RegionCode, row.Currency, row.PriceID, row.PreTaxAmountMinor,
			row.TaxRate, row.TaxAmountMinor, row.AfterTaxAmountMinor, row.Reason, row.EffectiveAt,
		)
		if err != nil {
			return fmt.Errorf("insert override[%d]: %w", idx, mapErr(err))
		}
	}
	return nil
}
