import { ApiError, request } from "@/api/http";

export type VersionStatus = "draft" | "published" | "archived";
export type FxSyncMode = "manual_confirm" | "auto_apply";
export type FxSyncSchedule = "monthly" | "quarterly";
export type FxRunStatus = "pending_review" | "approved" | "applied" | "ignored" | "failed";
export type SourceType = "manual" | "copy_published" | "copy_archived" | "fx_auto";

export interface Paginated<T> {
  items: T[];
  page: number;
  pageSize: number;
  total: number;
}

export interface CashierTemplateSummary {
  templateId: string;
  templateName: string;
  fxSyncEnabled: boolean;
  fxSyncMode: FxSyncMode;
  fxSyncSchedule: FxSyncSchedule;
  status: string;
}

export interface CashierTemplateVersion {
  version: string;
  status: VersionStatus;
  sourceType?: SourceType;
  autoGenerated?: boolean;
  fxBaseDate?: string | null;
  checksum?: string;
  publishedAt?: string | null;
  createdAt?: string;
  updatedAt?: string;
}

export interface CashierPriceRow {
  id?: number;
  countryCode: string;
  regionCode: string;
  currency: string;
  priceId: string;
  preTaxAmountMinor: number;
  taxRate: number;
  taxAmountMinor: number;
  afterTaxAmountMinor: number;
  effectiveAt: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface FxSyncRun {
  runId: number;
  status: FxRunStatus;
  candidateVersion: string;
  triggeredAt: string;
  reviewedBy?: number | null;
  reviewedAt?: string | null;
  reviewNote?: string;
  diffSummary: Record<string, unknown>;
}

export interface CashierTemplateDetail {
  templateId: string;
  templateName: string;
  fxSyncEnabled: boolean;
  fxSyncMode: FxSyncMode;
  fxSyncSchedule: FxSyncSchedule;
  status: string;
  versions: CashierTemplateVersion[];
  fxSyncRuns?: FxSyncRun[];
}

export interface ListTemplatesQuery {
  page?: number;
  pageSize?: number;
  keyword?: string;
}

export interface CreateTemplatePayload {
  templateId: string;
  templateName: string;
  fxSyncEnabled?: boolean;
  fxSyncMode?: FxSyncMode;
  fxSyncSchedule?: FxSyncSchedule;
}

export interface CreateVersionPayload {
  sourceType?: Exclude<SourceType, "fx_auto">;
  sourceVersion?: string;
}

export interface CopyToDraftResult {
  version: string;
  status: VersionStatus;
  sourceType: SourceType;
}

// PUT rows 请求行：归一化职责在后端（compact §价格行 / 00 §5），
// 前端下发 major 金额字符串 + taxRate 字符串，由后端读 currency_specs 归一化为 minor。
export interface PutPriceRow {
  countryCode: string;
  regionCode: string;
  currency: string;
  priceId: string;
  preTaxAmount: string;
  taxRate: string;
  effectiveAt: string;
}

export interface PutRowsPayload {
  rows: PutPriceRow[];
}

export interface ApproveRunPayload {
  action?: "approve" | "ignore";
  reviewNote?: string;
}

export interface GameCashierProfile {
  templateId: string;
  appliedTemplateVersion: string;
  snapshotChecksum: string;
  appliedAt: string;
}

export interface BindGameCashierProfilePayload {
  templateId: string;
  templateVersion: string;
}

export interface GameCashierPriceOverride {
  countryCode: string;
  regionCode: string;
  currency: string;
  priceId: string;
  preTaxAmountMinor: number;
  // taxRate 为 DECIMAL(8,6)，跨栈统一以字符串承载（对齐后端 GET 响应 tax_rate::text
  // 与 cashier-template PutPriceRow 既有约定），避免 JSON number 与后端 string DTO 漂移。
  taxRate: string;
  taxAmountMinor: number;
  afterTaxAmountMinor: number;
  reason: string;
  effectiveAt: string;
}

export interface PutGameCashierPriceOverridesPayload {
  items: GameCashierPriceOverride[];
}

function buildQuery(params: Record<string, unknown>): string {
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined && value !== null && value !== "") {
      search.append(key, String(value));
    }
  }
  const query = search.toString();
  return query ? `?${query}` : "";
}

const enc = encodeURIComponent;

export function listCashierTemplates(query: ListTemplatesQuery = {}): Promise<Paginated<CashierTemplateSummary>> {
  return request<Paginated<CashierTemplateSummary>>(`/api/admin/cashier/templates${buildQuery({ ...query })}`);
}

export function createCashierTemplate(payload: CreateTemplatePayload): Promise<CashierTemplateSummary> {
  return request<CashierTemplateSummary>("/api/admin/cashier/templates", {
    method: "POST",
    body: JSON.stringify(payload)
  });
}

type RawTemplateDetail = Partial<CashierTemplateDetail> & {
  template?: CashierTemplateSummary;
  versions?: Array<Record<string, unknown>>;
};

function normalizeVersion(raw: Record<string, unknown>): CashierTemplateVersion {
  const version = raw.version ?? raw.Version;
  const status = raw.status ?? raw.Status;
  const sourceType = raw.sourceType ?? raw.SourceType;
  const publishedAt = raw.publishedAt ?? raw.PublishedAt;
  return {
    version: version == null ? "" : String(version),
    status: (status as VersionStatus) ?? "draft",
    sourceType: sourceType as SourceType | undefined,
    autoGenerated: Boolean(raw.autoGenerated ?? raw.AutoGenerated),
    fxBaseDate: (raw.fxBaseDate ?? raw.FXBaseDate ?? null) as string | null | undefined,
    checksum: (raw.checksum ?? raw.Checksum) as string | undefined,
    publishedAt: (publishedAt ?? null) as string | null | undefined,
    createdAt: (raw.createdAt ?? raw.CreatedAt) as string | undefined,
    updatedAt: (raw.updatedAt ?? raw.UpdatedAt) as string | undefined
  };
}

export async function getCashierTemplate(templateId: string): Promise<CashierTemplateDetail> {
  const raw = await request<RawTemplateDetail>(`/api/admin/cashier/templates/${enc(templateId)}`);
  const base = raw.template ?? raw;
  const versionSource = raw.versions ?? (raw as CashierTemplateDetail).versions ?? [];
  const normalizedVersions = versionSource.map((item) => {
    if (typeof item === "object" && item !== null && ("version" in item || "Version" in item)) {
      return normalizeVersion(item as unknown as Record<string, unknown>);
    }
    return item as CashierTemplateVersion;
  });

  return {
    templateId: base.templateId ?? templateId,
    templateName: base.templateName ?? "",
    fxSyncEnabled: base.fxSyncEnabled ?? true,
    fxSyncMode: base.fxSyncMode ?? "manual_confirm",
    fxSyncSchedule: base.fxSyncSchedule ?? "monthly",
    status: base.status ?? "draft",
    versions: normalizedVersions,
    fxSyncRuns: raw.fxSyncRuns ?? []
  };
}

export function createCashierTemplateVersion(templateId: string, payload: CreateVersionPayload = {}): Promise<CashierTemplateVersion> {
  return request<CashierTemplateVersion>(`/api/admin/cashier/templates/${enc(templateId)}/versions`, {
    method: "POST",
    body: JSON.stringify(payload)
  });
}

export function copyTemplateVersionToDraft(templateId: string, version: string): Promise<CopyToDraftResult> {
  return request<CopyToDraftResult>(`/api/admin/cashier/templates/${enc(templateId)}/versions/${enc(version)}/copy-to-draft`, {
    method: "POST",
    body: JSON.stringify({})
  });
}

export function getCashierPriceRows(templateId: string, version: string): Promise<{ items: CashierPriceRow[] }> {
  return request<{ items: CashierPriceRow[] }>(`/api/admin/cashier/templates/${enc(templateId)}/versions/${enc(version)}/rows`);
}

export function putCashierPriceRows(templateId: string, version: string, payload: PutRowsPayload): Promise<{ items: CashierPriceRow[] }> {
  return request<{ items: CashierPriceRow[] }>(`/api/admin/cashier/templates/${enc(templateId)}/versions/${enc(version)}/rows`, {
    method: "PUT",
    body: JSON.stringify(payload)
  });
}

export function publishCashierVersion(templateId: string, version: string): Promise<{ version: string; status: VersionStatus }> {
  return request<{ version: string; status: VersionStatus }>(
    `/api/admin/cashier/templates/${enc(templateId)}/versions/${enc(version)}/publish`,
    {
      method: "POST",
      body: JSON.stringify({})
    }
  );
}

export function triggerFxSyncRun(templateId: string): Promise<FxSyncRun> {
  return request<FxSyncRun>(`/api/admin/cashier/templates/${enc(templateId)}/fx-sync/runs`, {
    method: "POST",
    body: JSON.stringify({})
  });
}

export function approveFxSyncRun(runId: number, payload: ApproveRunPayload = {}): Promise<FxSyncRun> {
  return request<FxSyncRun>(`/api/admin/cashier/fx-sync-runs/${runId}/approve`, {
    method: "POST",
    body: JSON.stringify(payload)
  });
}

type RawGameCashierProfile = Partial<GameCashierProfile> & {
  templateVersion?: string;
  appliedTemplateVersionId?: string;
};

function normalizeGameCashierProfile(raw: RawGameCashierProfile): GameCashierProfile {
  return {
    templateId: String(raw.templateId ?? ""),
    appliedTemplateVersion: String(raw.appliedTemplateVersion ?? raw.templateVersion ?? raw.appliedTemplateVersionId ?? ""),
    snapshotChecksum: String(raw.snapshotChecksum ?? ""),
    appliedAt: String(raw.appliedAt ?? "")
  };
}

export async function getGameCashierProfile(gameId: string): Promise<GameCashierProfile | null> {
  try {
    const raw = await request<RawGameCashierProfile | null>(`/api/admin/games/${enc(gameId)}/cashier/profile`);
    if (!raw || !raw.templateId) {
      return null;
    }
    return normalizeGameCashierProfile(raw);
  } catch (err) {
    // 未绑定模板时后端返回 NOT_FOUND；游戏详情 Tab 应展示空态而非整页错误。
    if (err instanceof ApiError && err.code === "NOT_FOUND") {
      return null;
    }
    throw err;
  }
}

export async function putGameCashierProfile(gameId: string, payload: BindGameCashierProfilePayload): Promise<GameCashierProfile> {
  const raw = await request<RawGameCashierProfile>(`/api/admin/games/${enc(gameId)}/cashier/profile`, {
    method: "PUT",
    body: JSON.stringify(payload)
  });
  return normalizeGameCashierProfile(raw);
}

export async function getGameCashierPriceOverrides(gameId: string): Promise<{ items: GameCashierPriceOverride[] }> {
  const res = await request<{ items?: GameCashierPriceOverride[] }>(`/api/admin/games/${enc(gameId)}/cashier/price-overrides`);
  return { items: res.items ?? [] };
}

export async function putGameCashierPriceOverrides(
  gameId: string,
  payload: PutGameCashierPriceOverridesPayload
): Promise<{ items: GameCashierPriceOverride[] }> {
  const res = await request<{ items?: GameCashierPriceOverride[] }>(`/api/admin/games/${enc(gameId)}/cashier/price-overrides`, {
    method: "PUT",
    body: JSON.stringify(payload)
  });
  return { items: res.items ?? [] };
}
