package cashier

import (
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"strconv"
	"strings"
	"time"

	cashierapp "github.com/csw/console/services/admin-api/internal/app/cashier"
	domaincashier "github.com/csw/console/services/admin-api/internal/domain/cashier"
	"github.com/csw/console/services/admin-api/internal/transport/http/httpx"
	"github.com/go-chi/chi/v5"
)

type Handler struct {
	svc *cashierapp.Service
}

func NewHandler(svc *cashierapp.Service) *Handler {
	return &Handler{svc: svc}
}

type createTemplateRequest struct {
	TemplateID     string `json:"templateId"`
	TemplateName   string `json:"templateName"`
	FXSyncEnabled  bool   `json:"fxSyncEnabled"`
	FXSyncMode     string `json:"fxSyncMode"`
	FXSyncSchedule string `json:"fxSyncSchedule"`
}

type createVersionRequest struct {
	SourceType    string `json:"sourceType"`
	SourceVersion string `json:"sourceVersion"`
}

type upsertRowsRequest struct {
	Rows []struct {
		CountryCode  string `json:"countryCode"`
		RegionCode   string `json:"regionCode"`
		Currency     string `json:"currency"`
		PriceID      string `json:"priceId"`
		PreTaxAmount string `json:"preTaxAmount"`
		TaxRate      string `json:"taxRate"`
		EffectiveAt  string `json:"effectiveAt"`
	} `json:"rows"`
}

type approveFXRunRequest struct {
	ReviewNote string `json:"reviewNote"`
	Action     string `json:"action"`
}

type versionResponse struct {
	Version       int     `json:"version"`
	Status        string  `json:"status"`
	SourceType    string  `json:"sourceType,omitempty"`
	AutoGenerated bool    `json:"autoGenerated,omitempty"`
	PublishedAt   *string `json:"publishedAt,omitempty"`
	CreatedAt     string  `json:"createdAt,omitempty"`
}

type fxRunResponse struct {
	RunID            int64          `json:"runId"`
	CandidateVersion string         `json:"candidateVersion"`
	Status           string         `json:"status"`
	DiffSummary      map[string]any `json:"diffSummary"`
	TriggeredAt      string         `json:"triggeredAt"`
	ReviewedBy       *int64         `json:"reviewedBy,omitempty"`
	ReviewedAt       *string        `json:"reviewedAt,omitempty"`
	ReviewNote       string         `json:"reviewNote"`
}

type templateResponse struct {
	TemplateID     string `json:"templateId"`
	TemplateName   string `json:"templateName"`
	FXSyncEnabled  bool   `json:"fxSyncEnabled"`
	FXSyncMode     string `json:"fxSyncMode"`
	FXSyncSchedule string `json:"fxSyncSchedule"`
	Status         string `json:"status"`
}

func toTemplateResponse(t domaincashier.PriceTemplate) templateResponse {
	return templateResponse{
		TemplateID:     t.TemplateID,
		TemplateName:   t.TemplateName,
		FXSyncEnabled:  t.FXSyncEnabled,
		FXSyncMode:     t.FXSyncMode,
		FXSyncSchedule: t.FXSyncSchedule,
		Status:         t.Status,
	}
}

func toVersionResponse(v domaincashier.TemplateVersionRecord) versionResponse {
	out := versionResponse{
		Version:       v.Version,
		Status:        string(v.Status),
		SourceType:    string(v.SourceType),
		AutoGenerated: v.AutoGenerated,
		CreatedAt:     v.CreatedAt.UTC().Format(time.RFC3339),
	}
	if v.PublishedAt != nil {
		s := v.PublishedAt.UTC().Format(time.RFC3339)
		out.PublishedAt = &s
	}
	return out
}

func toFXRunResponse(v cashierapp.FXSyncRunView) fxRunResponse {
	r := v.Run
	out := fxRunResponse{
		RunID:            r.ID,
		CandidateVersion: strconv.Itoa(v.CandidateVersion),
		Status:           string(r.Status),
		DiffSummary:      r.DiffSummaryJSON,
		TriggeredAt:      r.TriggeredAt.UTC().Format(time.RFC3339),
		ReviewedBy:       r.ReviewedBy,
		ReviewNote:       r.ReviewNote,
	}
	if r.ReviewedAt != nil {
		s := r.ReviewedAt.UTC().Format(time.RFC3339)
		out.ReviewedAt = &s
	}
	return out
}

func mapFXRuns(items []cashierapp.FXSyncRunView) []fxRunResponse {
	out := make([]fxRunResponse, 0, len(items))
	for _, item := range items {
		out = append(out, toFXRunResponse(item))
	}
	return out
}

func (h *Handler) ListTemplates(w http.ResponseWriter, r *http.Request) {
	page, pageSize := parsePage(r)
	items, total, err := h.svc.ListTemplates(r.Context(), page, pageSize)
	if err != nil {
		writeError(w, err)
		return
	}
	httpx.WriteData(w, http.StatusOK, map[string]any{
		"items":    items,
		"page":     page,
		"pageSize": pageSize,
		"total":    total,
	})
}

func (h *Handler) CreateTemplate(w http.ResponseWriter, r *http.Request) {
	var req createTemplateRequest
	if err := decodeJSON(r, &req); err != nil {
		httpx.WriteError(w, http.StatusBadRequest, httpx.CodeValidation, "请求体格式错误")
		return
	}
	if req.FXSyncMode == "" {
		req.FXSyncMode = "manual_confirm"
	}
	if req.FXSyncSchedule == "" {
		req.FXSyncSchedule = "monthly"
	}
	created, err := h.svc.CreateTemplate(r.Context(), cashierapp.CreateTemplateInput{
		TemplateID:     req.TemplateID,
		TemplateName:   req.TemplateName,
		FXSyncEnabled:  req.FXSyncEnabled,
		FXSyncMode:     req.FXSyncMode,
		FXSyncSchedule: req.FXSyncSchedule,
	})
	if err != nil {
		writeError(w, err)
		return
	}
	httpx.WriteData(w, http.StatusCreated, created)
}

func (h *Handler) GetTemplate(w http.ResponseWriter, r *http.Request) {
	templateID := chi.URLParam(r, "templateId")
	tpl, versions, err := h.svc.GetTemplate(r.Context(), templateID)
	if err != nil {
		writeError(w, err)
		return
	}
	runs, err := h.svc.ListFXSyncRuns(r.Context(), templateID)
	if err != nil {
		writeError(w, err)
		return
	}
	httpx.WriteData(w, http.StatusOK, map[string]any{
		"template":   toTemplateResponse(tpl),
		"versions":   mapVersions(versions),
		"fxSyncRuns": mapFXRuns(runs),
	})
}

func (h *Handler) CreateVersion(w http.ResponseWriter, r *http.Request) {
	var req createVersionRequest
	if err := decodeJSON(r, &req); err != nil {
		httpx.WriteError(w, http.StatusBadRequest, httpx.CodeValidation, "请求体格式错误")
		return
	}
	sourceType := domaincashier.SourceType(req.SourceType)
	if sourceType == "" {
		sourceType = domaincashier.SourceTypeManual
	}
	sourceVersion := 0
	if raw := strings.TrimSpace(req.SourceVersion); raw != "" {
		v, convErr := strconv.Atoi(raw)
		if convErr != nil || v <= 0 {
			httpx.WriteError(w, http.StatusBadRequest, httpx.CodeValidation, "sourceVersion 非法")
			return
		}
		sourceVersion = v
	}
	record, err := h.svc.CreateVersion(r.Context(), cashierapp.CreateVersionInput{
		TemplateID:    chi.URLParam(r, "templateId"),
		SourceType:    sourceType,
		SourceVersion: sourceVersion,
	})
	if err != nil {
		writeError(w, err)
		return
	}
	httpx.WriteData(w, http.StatusCreated, toVersionResponse(record))
}

func (h *Handler) CopyToDraft(w http.ResponseWriter, r *http.Request) {
	version, ok := parseVersion(w, r)
	if !ok {
		return
	}
	out, err := h.svc.CopyToDraft(r.Context(), chi.URLParam(r, "templateId"), version)
	if err != nil {
		writeError(w, err)
		return
	}
	httpx.WriteData(w, http.StatusCreated, out)
}

func (h *Handler) ListRows(w http.ResponseWriter, r *http.Request) {
	version, ok := parseVersion(w, r)
	if !ok {
		return
	}
	rows, err := h.svc.ListRows(r.Context(), chi.URLParam(r, "templateId"), version)
	if err != nil {
		writeError(w, err)
		return
	}
	httpx.WriteData(w, http.StatusOK, map[string]any{"items": rows})
}

func (h *Handler) UpsertRows(w http.ResponseWriter, r *http.Request) {
	version, ok := parseVersion(w, r)
	if !ok {
		return
	}
	var req upsertRowsRequest
	if err := decodeJSON(r, &req); err != nil {
		httpx.WriteError(w, http.StatusBadRequest, httpx.CodeValidation, "请求体格式错误")
		return
	}
	rows := make([]cashierapp.UpsertPriceRowInput, 0, len(req.Rows))
	for _, item := range req.Rows {
		effectiveAt, err := time.Parse(time.RFC3339, item.EffectiveAt)
		if err != nil {
			httpx.WriteError(w, http.StatusBadRequest, httpx.CodeValidation, "effectiveAt 非法")
			return
		}
		rows = append(rows, cashierapp.UpsertPriceRowInput{
			CountryCode:  item.CountryCode,
			RegionCode:   item.RegionCode,
			Currency:     item.Currency,
			PriceID:      item.PriceID,
			PreTaxAmount: item.PreTaxAmount,
			TaxRate:      item.TaxRate,
			EffectiveAt:  effectiveAt,
		})
	}
	out, err := h.svc.UpsertRows(r.Context(), chi.URLParam(r, "templateId"), version, rows)
	if err != nil {
		writeError(w, err)
		return
	}
	httpx.WriteData(w, http.StatusOK, map[string]any{"items": out})
}

func (h *Handler) PublishVersion(w http.ResponseWriter, r *http.Request) {
	version, ok := parseVersion(w, r)
	if !ok {
		return
	}
	if err := h.svc.PublishVersion(r.Context(), chi.URLParam(r, "templateId"), version); err != nil {
		writeError(w, err)
		return
	}
	httpx.WriteData(w, http.StatusOK, map[string]any{"status": "published"})
}

func (h *Handler) CreateFXRun(w http.ResponseWriter, r *http.Request) {
	view, err := h.svc.TriggerFXSyncRun(r.Context(), chi.URLParam(r, "templateId"))
	if err != nil {
		writeError(w, err)
		return
	}
	httpx.WriteData(w, http.StatusCreated, toFXRunResponse(view))
}

func (h *Handler) ApproveFXRun(w http.ResponseWriter, r *http.Request) {
	runID, ok := parseRunID(w, r)
	if !ok {
		return
	}
	var req approveFXRunRequest
	if err := decodeJSON(r, &req); err != nil && !errors.Is(err, io.EOF) {
		httpx.WriteError(w, http.StatusBadRequest, httpx.CodeValidation, "请求体格式错误")
		return
	}
	var err error
	if req.Action == "ignore" {
		err = h.svc.IgnoreFXSyncRun(r.Context(), runID, req.ReviewNote)
	} else {
		err = h.svc.ApproveFXSyncRun(r.Context(), runID, req.ReviewNote)
	}
	if err != nil {
		writeError(w, err)
		return
	}
	status := "applied"
	if req.Action == "ignore" {
		status = "ignored"
	}
	httpx.WriteData(w, http.StatusOK, map[string]any{"status": status})
}

func mapVersions(items []domaincashier.TemplateVersionRecord) []versionResponse {
	out := make([]versionResponse, 0, len(items))
	for _, item := range items {
		out = append(out, toVersionResponse(item))
	}
	return out
}

func writeError(w http.ResponseWriter, err error) {
	var appErr *cashierapp.Error
	if errors.As(err, &appErr) {
		httpx.WriteError(w, appErr.Status, appErr.Code, appErr.Message, appErr.Details...)
		return
	}
	httpx.WriteAppError(w, err)
}

func parseVersion(w http.ResponseWriter, r *http.Request) (int, bool) {
	raw := chi.URLParam(r, "version")
	v, err := strconv.Atoi(raw)
	if err != nil || v <= 0 {
		httpx.WriteError(w, http.StatusBadRequest, httpx.CodeValidation, "version 非法")
		return 0, false
	}
	return v, true
}

func parseRunID(w http.ResponseWriter, r *http.Request) (int64, bool) {
	raw := chi.URLParam(r, "runId")
	v, err := strconv.ParseInt(raw, 10, 64)
	if err != nil || v <= 0 {
		httpx.WriteError(w, http.StatusBadRequest, httpx.CodeValidation, "runId 非法")
		return 0, false
	}
	return v, true
}

func parsePage(r *http.Request) (int, int) {
	page := 1
	pageSize := 20
	if s := r.URL.Query().Get("page"); s != "" {
		if v, err := strconv.Atoi(s); err == nil && v > 0 {
			page = v
		}
	}
	if s := r.URL.Query().Get("pageSize"); s != "" {
		if v, err := strconv.Atoi(s); err == nil && v > 0 {
			pageSize = v
		}
	}
	if pageSize > 100 {
		pageSize = 100
	}
	return page, pageSize
}

func decodeJSON(r *http.Request, target any) error {
	if r.Body == nil {
		return nil
	}
	dec := json.NewDecoder(r.Body)
	return dec.Decode(target)
}
