package cashier

import (
	"crypto/sha256"
	"encoding/hex"
	"sort"
	"strconv"
	"strings"
	"time"
)

type FXRunStatus string

const (
	FXRunPendingReview FXRunStatus = "pending_review"
	FXRunApproved      FXRunStatus = "approved"
	FXRunApplied       FXRunStatus = "applied"
	FXRunIgnored       FXRunStatus = "ignored"
	FXRunFailed        FXRunStatus = "failed"
)

type PriceTemplate struct {
	ID             int64  `json:"id"`
	TemplateID     string `json:"templateId"`
	TemplateName   string `json:"templateName"`
	FXSyncEnabled  bool   `json:"fxSyncEnabled"`
	FXSyncMode     string `json:"fxSyncMode"`
	FXSyncSchedule string `json:"fxSyncSchedule"`
	Status         string `json:"status"`
}

type PriceRow struct {
	ID                   int64  `json:"id,omitempty"`
	TemplateVersionIDRef int64  `json:"templateVersionIdRef,omitempty"`
	CountryCode          string `json:"countryCode"`
	RegionCode           string `json:"regionCode"`
	Currency             string `json:"currency"`
	PriceID              string `json:"priceId"`
	PreTaxAmountMinor    int64  `json:"preTaxAmountMinor"`
	TaxRate              string `json:"taxRate"`
	TaxAmountMinor       int64  `json:"taxAmountMinor"`
	AfterTaxAmountMinor  int64  `json:"afterTaxAmountMinor"`
	EffectiveAt          string `json:"effectiveAt"`
}

type TemplateVersionRecord struct {
	ID            int64
	TemplateIDRef int64
	Version       int
	SourceType    SourceType
	AutoGenerated bool
	FXBaseDate    *time.Time
	Status        VersionStatus
	Checksum      string
	PublishedAt   *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// ComputeVersionChecksum 对某个模板版本的价格行集合计算确定性校验和（sha256 hex）。
// 用途：发布版本时固化该版本的价格内容指纹，游戏绑定时记录为 snapshot_checksum（00 §3.3 版本生命周期、
// game-cashier 绑定快照语义）。排序后仅纳入业务字段（不含 DB 主键/时间戳），保证同内容跨进程/库稳定一致。
func ComputeVersionChecksum(rows []PriceRow) string {
	keyed := make([]PriceRow, len(rows))
	copy(keyed, rows)
	sort.Slice(keyed, func(i, j int) bool {
		return rowChecksumKey(keyed[i]) < rowChecksumKey(keyed[j])
	})
	var b strings.Builder
	for _, row := range keyed {
		b.WriteString(row.CountryCode)
		b.WriteByte('|')
		b.WriteString(row.RegionCode)
		b.WriteByte('|')
		b.WriteString(row.Currency)
		b.WriteByte('|')
		b.WriteString(row.PriceID)
		b.WriteByte('|')
		b.WriteString(strconv.FormatInt(row.PreTaxAmountMinor, 10))
		b.WriteByte('|')
		b.WriteString(strings.TrimSpace(row.TaxRate))
		b.WriteByte('|')
		b.WriteString(strconv.FormatInt(row.TaxAmountMinor, 10))
		b.WriteByte('|')
		b.WriteString(strconv.FormatInt(row.AfterTaxAmountMinor, 10))
		b.WriteByte('|')
		b.WriteString(row.EffectiveAt)
		b.WriteByte('\n')
	}
	sum := sha256.Sum256([]byte(b.String()))
	return hex.EncodeToString(sum[:])
}

func rowChecksumKey(r PriceRow) string {
	return r.CountryCode + "|" + r.RegionCode + "|" + r.Currency + "|" + r.PriceID
}

type FXSyncRun struct {
	ID                    int64
	TemplateIDRef         int64
	CandidateVersionIDRef int64
	Status                FXRunStatus
	DiffSummaryJSON       map[string]any
	TriggeredAt           time.Time
	ReviewedBy            *int64
	ReviewedAt            *time.Time
	ReviewNote            string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}
