package cashier

import "time"

type FXRunStatus string

const (
	FXRunPendingReview FXRunStatus = "pending_review"
	FXRunApproved      FXRunStatus = "approved"
	FXRunApplied       FXRunStatus = "applied"
	FXRunIgnored       FXRunStatus = "ignored"
	FXRunFailed        FXRunStatus = "failed"
)

type PriceTemplate struct {
	ID             int64  `json:"id"`
	TemplateID     string `json:"templateId"`
	TemplateName   string `json:"templateName"`
	FXSyncEnabled  bool   `json:"fxSyncEnabled"`
	FXSyncMode     string `json:"fxSyncMode"`
	FXSyncSchedule string `json:"fxSyncSchedule"`
	Status         string `json:"status"`
}

type PriceRow struct {
	ID                   int64  `json:"id,omitempty"`
	TemplateVersionIDRef int64  `json:"templateVersionIdRef,omitempty"`
	CountryCode          string `json:"countryCode"`
	RegionCode           string `json:"regionCode"`
	Currency             string `json:"currency"`
	PriceID              string `json:"priceId"`
	PreTaxAmountMinor    int64  `json:"preTaxAmountMinor"`
	TaxRate              string `json:"taxRate"`
	TaxAmountMinor       int64  `json:"taxAmountMinor"`
	AfterTaxAmountMinor  int64  `json:"afterTaxAmountMinor"`
	EffectiveAt          string `json:"effectiveAt"`
}

type TemplateVersionRecord struct {
	ID            int64
	TemplateIDRef int64
	Version       int
	SourceType    SourceType
	AutoGenerated bool
	FXBaseDate    *time.Time
	Status        VersionStatus
	Checksum      string
	PublishedAt   *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type FXSyncRun struct {
	ID                    int64
	TemplateIDRef         int64
	CandidateVersionIDRef int64
	Status                FXRunStatus
	DiffSummaryJSON       map[string]any
	TriggeredAt           time.Time
	ReviewedBy            *int64
	ReviewedAt            *time.Time
	ReviewNote            string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}
